from __future__ import annotations
from typing import Protocol, List, Optional

from domain.models import Cluster, NewsItem


class RepositoryProtocol(Protocol):
    def list_clusters(self) -> List[Cluster]: ...
    def list_news(self, cluster_id: int) -> List[NewsItem]: ...
    def add_news(self, cluster_id: int, title: str, body: str) -> NewsItem: ...
    def delete_news(self, news_id: int) -> None: ...
    # опционально на будущее:
    # def update_news(self, news_id: int, title: Optional[str], body: Optional[str]) -> None: ...
